-- Insert penalty matrix data for different violation types and offense counts
INSERT INTO penalty_matrix (violation_type, offense_count, penalty_description) VALUES
-- Dress Code Violations
('No ID', 1, 'Warning'),
('No ID', 2, 'Grounding'),
('No ID', 3, 'Suspension'),
('Wearing of rubber slippers', 1, 'Warning'),
('Wearing of rubber slippers', 2, 'Grounding'),
('Wearing of rubber slippers', 3, 'Suspension'),
('Improper wearing of uniform', 1, 'Warning'),
('Improper wearing of uniform', 2, 'Grounding'),
('Improper wearing of uniform', 3, 'Suspension'),
('Non-prescribed haircut', 1, 'Warning'),
('Non-prescribed haircut', 2, 'Grounding'),
('Non-prescribed haircut', 3, 'Suspension'),
('Wearing of earring', 1, 'Warning'),
('Wearing of earring', 2, 'Grounding'),
('Wearing of earring', 3, 'Suspension'),
('Wearing of earrings', 1, 'Warning'),
('Wearing of earrings', 2, 'Grounding'),
('Wearing of earrings', 3, 'Suspension'),
('Wearing of multiple earrings', 1, 'Warning'),
('Wearing of multiple earrings', 2, 'Grounding'),
('Wearing of multiple earrings', 3, 'Suspension'),

-- Minor Offenses
('Using cellphones/ gadgets during class hours', 1, 'Warning'),
('Using cellphones/ gadgets during class hours', 2, 'Grounding'),
('Using cellphones/ gadgets during class hours', 3, 'Probation'),
('Using cellphones/ gadgets during class hours.', 1, 'Warning'),
('Using cellphones/ gadgets during class hours.', 2, 'Grounding'),
('Using cellphones/ gadgets during class hours.', 3, 'Probation'),
('Eating inside the laboratories', 1, 'Warning'),
('Eating inside the laboratories', 2, 'Grounding'),
('Eating inside the laboratories', 3, 'Community service'),
('Improper not wearing/ tampering of ID', 1, 'Warning'),
('Improper not wearing/ tampering of ID', 2, 'Grounding'),
('Improper not wearing/ tampering of ID', 3, 'Probation'),
('Improper/tampered ID', 1, 'Warning'),
('Improper/tampered ID', 2, 'Grounding'),
('Improper/tampered ID', 3, 'Probation'),
('Improper hairstyle', 1, 'Warning'),
('Improper hairstyle', 2, 'Grounding'),
('Improper hairstyle', 3, 'Suspension'),
('Improper Uniform', 1, 'Warning'),
('Improper Uniform', 2, 'Grounding'),
('Improper Uniform', 3, 'Suspension'),

-- Major Offenses
('Stealing', 1, 'Suspension'),
('Stealing', 2, 'Non-readmission'),
('Stealing', 3, 'Expulsion'),
('Vandalism', 1, 'Suspension'),
('Vandalism', 2, 'Community service + Probation'),
('Vandalism', 3, 'Expulsion'),
('Verbal assault', 1, 'Probation'),
('Verbal assault', 2, 'Suspension'),
('Verbal assault', 3, 'Non-readmission'),
('Organizing, planning or joining to any group or fraternity activity', 1, 'Suspension'),
('Organizing, planning or joining to any group or fraternity activity', 2, 'Non-readmission'),
('Organizing, planning or joining to any group or fraternity activity', 3, 'Expulsion'),
('Organizing, planning or joining to any group or fraternity activity.', 1, 'Suspension'),
('Organizing, planning or joining to any group or fraternity activity.', 2, 'Non-readmission'),
('Organizing, planning or joining to any group or fraternity activity.', 3, 'Expulsion'),
('Organizing/joining fraternity activities', 1, 'Suspension'),
('Organizing/joining fraternity activities', 2, 'Non-readmission'),
('Organizing/joining fraternity activities', 3, 'Expulsion'),

-- Conduct Violations
('Cutting Classes', 1, 'Warning'),
('Cutting Classes', 2, 'Grounding'),
('Cutting Classes', 3, 'Suspension'),
('Cheating/Academic Dishonesty', 1, 'Suspension'),
('Cheating/Academic Dishonesty', 2, 'Probation'),
('Cheating/Academic Dishonesty', 3, 'Expulsion'),
('Cheating / Academic Dishonesty', 1, 'Suspension'),
('Cheating / Academic Dishonesty', 2, 'Probation'),
('Cheating / Academic Dishonesty', 3, 'Expulsion'),
('Theft/Stealing', 1, 'Suspension'),
('Theft/Stealing', 2, 'Non-readmission'),
('Theft/Stealing', 3, 'Expulsion'),
('Theft / Stealing', 1, 'Suspension'),
('Theft / Stealing', 2, 'Non-readmission'),
('Theft / Stealing', 3, 'Expulsion'),
('Inflicting/Direct Assault', 1, 'Suspension'),
('Inflicting/Direct Assault', 2, 'Non-readmission'),
('Inflicting/Direct Assault', 3, 'Expulsion'),
('Inflicting / Direct Assault', 1, 'Suspension'),
('Inflicting / Direct Assault', 2, 'Non-readmission'),
('Inflicting / Direct Assault', 3, 'Expulsion'),
('Gambling', 1, 'Probation'),
('Gambling', 2, 'Suspension'),
('Gambling', 3, 'Expulsion'),
('Smoking within the school vicinity', 1, 'Grounding'),
('Smoking within the school vicinity', 2, 'Suspension'),
('Smoking within the school vicinity', 3, 'Expulsion'),
('Smoking within the school', 1, 'Grounding'),
('Smoking within the school', 2, 'Suspension'),
('Smoking within the school', 3, 'Expulsion'),
('Possession/Use of Prohibited Drugs', 1, 'Suspension'),
('Possession/Use of Prohibited Drugs', 2, 'Non-readmission'),
('Possession/Use of Prohibited Drugs', 3, 'Expulsion'),
('Use/Possession of Prohibited Drugs', 1, 'Suspension'),
('Use/Possession of Prohibited Drugs', 2, 'Non-readmission'),
('Use/Possession of Prohibited Drugs', 3, 'Expulsion'),
('Possession/Use of Liquor/Alcoholic Beverages', 1, 'Suspension'),
('Possession/Use of Liquor/Alcoholic Beverages', 2, 'Non-readmission'),
('Possession/Use of Liquor/Alcoholic Beverages', 3, 'Expulsion'),
('Use/Possession of Liquor/Alcohol', 1, 'Suspension'),
('Use/Possession of Liquor/Alcohol', 2, 'Non-readmission'),
('Use/Possession of Liquor/Alcohol', 3, 'Expulsion'),
('Others', 1, 'Warning/Probation'),
('Others', 2, 'Suspension'),
('Others', 3, 'Expulsion');